# Generated by Django 3.2.8 on 2021-11-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='type',
            new_name='ship_type',
        ),
    ]
