# Generated by Django 3.2.8 on 2021-11-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_type_ship_ship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Resupply Date')),
                ('meal', models.CharField(choices=[('F', 'Fuel'), ('W', 'Water'), ('O', 'Oxygen'), ('F', 'Food/Filters/Medicines/Tools')], default='F', max_length=1)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ship')),
            ],
        ),
    ]
