# Generated by Django 3.2.8 on 2021-11-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_resupply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resupply',
            options={'ordering': ['-date']},
        ),
    ]
