# Generated by Django 3.2.8 on 2021-11-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_resupply_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resupply',
            old_name='meal',
            new_name='supply',
        ),
    ]
