# Generated by Django 3.2.8 on 2021-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_meal_resupply_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='resupply',
            name='supply',
            field=models.CharField(choices=[('F', 'Fuel Pellets'), ('W', 'Water'), ('O', 'Oxygen'), ('M', 'Food/Medicines/Filters/Tools')], default='F', max_length=1, verbose_name='Resupply Type'),
        ),
        migrations.AddField(
            model_name='ship',
            name='equipment',
            field=models.ManyToManyField(to='main_app.Equipment'),
        ),
    ]
